# Generated by Django 4.1.7 on 2023-03-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='birth_date',
            new_name='BirthDate',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='employee',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='is_deleted',
            new_name='IsDeleted',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='relationship',
            new_name='Relationship',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='hire_date',
            new_name='HireDate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_deleted',
            new_name='IsDeleted',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='job_position',
            new_name='JobPosition',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='photo',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='wage',
            new_name='Wage',
        ),
    ]
