# Generated by Django 4.1.7 on 2023-03-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_birth_date_beneficiary_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='Employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='Beneficiary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.beneficiary'),
            preserve_default=False,
        ),
    ]
